'use client';

import Link from 'next/link';
import Image from 'next/image';
import { useEffect, useRef } from 'react';

/**
 * Site-wide footer for every non-homepage route. It is a pixel match for the
 * footer inside the homepage iframe: the outlined "FOUNDRIE AI" word (molten
 * FOUNDRIE + silver AI on hover) drifting horizontally as it scrolls into view,
 * the molten newsletter kicker, and the same grid and legal base.
 */
export function SiteFooter() {
  const wordRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const word = wordRef.current;
    if (!word) return;
    if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return;

    let raf = 0;
    const update = () => {
      raf = 0;
      const footer = word.closest('footer');
      if (!footer) return;
      const rect = footer.getBoundingClientRect();
      const vh = window.innerHeight || document.documentElement.clientHeight;
      // 0 when the footer top reaches the viewport bottom, 1 when its bottom does.
      const p = Math.min(1, Math.max(0, (vh - rect.top) / (rect.height || 1)));
      word.style.transform = `translateX(${(-3 + p * 6).toFixed(3)}%)`;
    };
    const onScroll = () => {
      if (!raf) raf = requestAnimationFrame(update);
    };

    update();
    window.addEventListener('scroll', onScroll, { passive: true });
    window.addEventListener('resize', onScroll);
    return () => {
      window.removeEventListener('scroll', onScroll);
      window.removeEventListener('resize', onScroll);
      if (raf) cancelAnimationFrame(raf);
    };
  }, []);

  return (
    <footer className="foundrie-site-footer mt-auto print:block relative z-50">
      <div className="container">
        <div className="foundrie-footer-word" ref={wordRef} aria-hidden="true">
          <span className="wf">FOUNDRIE</span>&nbsp;<span className="wa">AI</span>
        </div>
        <div className="foundrie-newsletter">
          <span className="foundrie-footer-kicker">STAY IN THE LOOP &gt;</span>
          <div className="foundrie-newsletter-row">
            <input type="email" placeholder="you@company.com" aria-label="Email address" />
            <button type="button">Join the List &gt;</button>
          </div>
        </div>
        <div className="foundrie-footer-grid">
          <div>
            <Image
              src="https://thesiliconhill.com/wp-content/uploads/2026/07/Artboard-103g.png"
              alt="Foundrie AI"
              width={360}
              height={64}
              className="foundrie-footer-logo"
            />
            <p className="foundrie-footer-tagline">START FORGING YOUR OWN FUTURE.</p>
          </div>
          <div className="foundrie-footer-cols">
            <div>
              <h4>Platform</h4>
              <Link href="/#career">Career</Link>
              <Link href="/#platform">Company</Link>
              <Link href="/resources">Resources</Link>
              <Link href="/pricing">Pricing</Link>
            </div>
            <div>
              <h4>Company</h4>
              <Link href="/about">About</Link>
              <Link href="/connect">Connect</Link>
              <Link href="/help">Help Desk</Link>
              <Link href="/login">Sign In</Link>
            </div>
            <div>
              <h4>Legal</h4>
              <Link href="/terms">Terms of Service</Link>
              <Link href="/privacy">Privacy Policy</Link>
              <Link href="/cookies">Cookie Policy</Link>
            </div>
          </div>
        </div>
        <div className="foundrie-footer-base">
          <span>&copy; 2026 Foundrie AI. All Rights Reserved.</span>
          <span>Forged in Northern Virginia.</span>
          <p>
            DISCLAIMER: Foundrie AI provides tools for educational and informational purposes only.
            Content generated by our tools does not constitute legal, financial, investment, or
            professional advice. Always verify important decisions with qualified professionals.
          </p>
        </div>
      </div>
    </footer>
  );
}
