import type { Metadata } from 'next';
import { Toaster } from "@/components/ui/toaster"
import './globals.css';
import { FirebaseClientProvider } from '@/firebase';
import { AppHeader } from '@/components/shared/app-header';
import { AppSidebar } from '@/components/shared/app-sidebar';
import Link from 'next/link';
import Image from 'next/image';
import { ActionArrowNormalizer } from '@/components/shared/action-arrow-normalizer';

export const metadata: Metadata = {
  metadataBase: new URL('https://foundrie.ai'),
  title: {
    default: 'Foundrie AI — Your Innovation Destination',
    template: '%s · Foundrie AI',
  },
  description:
    'Two suites of intelligent tools for the AI era of business. Build your company with LaunchCode and your career with Resumait — all in one place.',
  openGraph: {
    title: 'Foundrie AI — Your Innovation Destination',
    description:
      'Two suites of intelligent tools for the AI era of business. Build your company with LaunchCode and your career with Resumait — all in one place.',
    type: 'website',
    siteName: 'Foundrie AI',
  },
  twitter: { card: 'summary_large_image' },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark overflow-x-clip">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@600;700&display=swap" rel="stylesheet" />
      </head>
      <body className="font-body antialiased bg-background min-h-screen flex flex-col overflow-x-clip">
        <FirebaseClientProvider>
          <AppHeader />
          <ActionArrowNormalizer />
          <div className="flex-grow flex relative">
            <AppSidebar />
            <div className="flex-1 flex flex-col relative min-w-0">
              {children}
              <footer className="foundrie-site-footer mt-auto print:block relative z-50">
                <div className="container">
                  <div className="foundrie-footer-word" aria-hidden="true">FOUNDRIE&nbsp;AI</div>
                  <div className="foundrie-newsletter">
                    <span className="foundrie-footer-kicker">STAY IN THE LOOP &gt;</span>
                    <div className="foundrie-newsletter-row">
                      <input type="email" placeholder="you@company.com" aria-label="Email address" />
                      <button type="button">Join the List &gt;</button>
                    </div>
                  </div>
                  <div className="foundrie-footer-grid">
                    <div>
                      <Image
                        src="https://thesiliconhill.com/wp-content/uploads/2026/07/Artboard-103g.png"
                        alt="Foundrie AI"
                        width={300}
                        height={52}
                        className="foundrie-footer-logo"
                      />
                      <p>START FORGING YOUR OWN FUTURE.</p>
                    </div>
                    <div className="foundrie-footer-cols">
                      <div><h4>Platform</h4><Link href="/career">Career</Link><Link href="/company">Company</Link><Link href="/resources">Resources</Link><Link href="/pricing">Pricing</Link></div>
                      <div><h4>Company</h4><Link href="/about">About</Link><Link href="/connect">Connect</Link><Link href="/login">Sign In</Link></div>
                      <div><h4>Legal</h4><Link href="/terms">Terms of Service</Link><Link href="/privacy">Privacy Policy</Link><Link href="/cookies">Cookie Policy</Link></div>
                    </div>
                  </div>
                  <div className="foundrie-footer-base">
                    <span>&copy; 2026 Foundrie AI. All Rights Reserved.</span>
                    <span>Forged in Northern Virginia.</span>
                    <p>DISCLAIMER: Foundrie AI provides tools for educational and informational purposes only. Content generated by our tools does not constitute legal, financial, investment, or professional advice. Always verify important decisions with qualified professionals.</p>
                  </div>
                </div>
              </footer>
            </div>
          </div>
          <Toaster />
        </FirebaseClientProvider>
      </body>
    </html>
  );
}
