import { LegalPage } from '@/components/legal/legal-page';

export const metadata = {
  title: 'Terms of Service',
  description: 'The terms that govern your use of the Foundrie AI platform.',
};

export default function TermsPage() {
  return (
    <LegalPage
      title="Terms of Service"
      updated="July 3, 2026"
      intro="These Terms govern access to Foundrie AI, including LaunchCode, Resumait, BrandForge, and related services. By using the platform, users agree to use Foundrie AI responsibly, verify important outputs, and understand that AI-generated material is a decision-support tool rather than a substitute for professional judgment."
      sections={[
        {
          title: '1. Platform Purpose',
          body: [
            'Foundrie AI provides AI-native tools for career development, brand building, startup ideation, validation, company execution, and related educational workflows.',
            'The platform is designed to help users create, organize, analyze, and improve materials. It does not guarantee employment, investment, funding, sales, business formation, regulatory compliance, or any specific commercial outcome.',
          ],
        },
        {
          title: '2. User Responsibilities',
          body: [
            'Users are responsible for the information they submit, the decisions they make, and the way they use generated content. Users should not submit content they do not have the right to use.',
            'Users must verify important business, career, legal, financial, investment, tax, employment, or compliance decisions with qualified professionals before acting.',
          ],
        },
        {
          title: '3. AI-Generated Content',
          body: [
            'Foundrie AI uses artificial intelligence to generate analysis, drafts, recommendations, scores, summaries, reports, and other content. AI output may be incomplete, outdated, inaccurate, or inappropriate for a particular situation.',
            'Users may use generated content as a starting point, but they remain responsible for review, editing, factual verification, and final use.',
          ],
        },
        {
          title: '4. Acceptable Use',
          body: [
            'Users may not use Foundrie AI to violate law, infringe intellectual property rights, misrepresent credentials, fabricate achievements, deceive employers, deceive investors, harass others, create unlawful content, or bypass platform security.',
            'Foundrie AI may limit, suspend, or terminate access for misuse, abusive usage, attempts to compromise the platform, or activity that creates legal, security, or operational risk.',
          ],
        },
        {
          title: '5. Accounts, Admin, and Data',
          body: [
            'Users are responsible for maintaining account security. Administrators may access account, usage, tool, and generated-output data as needed to operate, secure, debug, support, and improve the platform.',
            'In development and testing environments, administrator tools may include broader diagnostic access so that platform behavior, AI cost, and user journeys can be verified before production launch.',
          ],
        },
        {
          title: '6. Professional Advice Disclaimer',
          body: [
            'Foundrie AI provides tools for educational and informational purposes only. Content generated by our tools does not constitute legal, financial, investment, employment, tax, medical, or other professional advice.',
            'Users should always verify important decisions with qualified professionals.',
          ],
        },
      ]}
    />
  );
}
